In [9]:
import pandas as pd
import numpy as np
import matplotlib as mlp
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

print("Done Import")

Done Import

In [10]:
pd.set_option('display.max_rows', 5)
pd.set_option('display.max_columns', None)

applemob = pd.read_excel("apple-mobility-index.xlsx")
applemob

,Value,Date,Sub-Sector,Super Region,Commodity And Exchange,Frequency,Source,Indicator
0,393834.0,2020-08-07,COMMODITY PRICES,GLOBAL DATA,NYMEX CRUDE OIL FUTURES,DAILY,COMMODITY EXCHANGE,VOLUME
1,865736.0,2018-03-07,COMMODITY PRICES,GLOBAL DATA,NYMEX CRUDE OIL FUTURES,DAILY,COMMODITY EXCHANGE,VOLUME
...,...,...,...,...,...,...,...,...
16998,444816.0,2019-07-09,COMMODITY PRICES,GLOBAL DATA,ICE BRENT CRUDE OIL FUTURES,DAILY,COMMODITY EXCHANGE,PREV# DAY OPEN INTEREST
16999,535856.0,2017-07-31,COMMODITY PRICES,GLOBAL DATA,ICE BRENT CRUDE OIL FUTURES,DAILY,COMMODITY EXCHANGE,PREV# DAY OPEN INTEREST

In [11]:
pd.set_option('display.max_rows', None)
print(applemob.info(verbose=True),'\n','-'*80,'\n','-'*80)
applemob_desc = pd.DataFrame()
applemob_desc['isna'] = applemob.isna().sum()
applemob_desc['nunique'] = applemob.nunique()
print(applemob_desc)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Value                   17000 non-null  float64
 1   Date                    17000 non-null  object
 2   Sub-Sector              17000 non-null  object
 3   Super Region            17000 non-null  object
 4   Commodity And Exchange  17000 non-null  object
 5   Frequency               17000 non-null  object
 6   Source                  17000 non-null  object
 7   Indicator               17000 non-null  object
dtypes: float64(1), object(7)
memory usage: 1.0+ MB
None
 --------------------------------------------------------------------------------
 --------------------------------------------------------------------------------
                        isna  nunique
Value                      0     8749
Date                       0     1103
Sub-Sector                 0        1
Super Region               0        1
Commodity And Exchange     0        4
Frequency                  0        1
Source                     0        1
Indicator                  0       10

In [12]:
pd.set_option('display.max_rows', 10)
applemob = applemob.drop(['Sub-Sector', 'Super Region', 'Frequency', 'Source'], axis=1)

applemob['Date'] = pd.to_datetime(applemob['Date'])
applemob

,Value,Date,Commodity And Exchange,Indicator
0,393834.0,2020-08-07,NYMEX CRUDE OIL FUTURES,VOLUME
1,865736.0,2018-03-07,NYMEX CRUDE OIL FUTURES,VOLUME
2,345299.0,2021-01-25,NYMEX CRUDE OIL FUTURES,VOLUME
3,353417.0,2020-08-06,NYMEX CRUDE OIL FUTURES,VOLUME
4,626407.0,2018-03-06,NYMEX CRUDE OIL FUTURES,VOLUME
...,...,...,...,...
16995,465881.0,2019-07-05,ICE BRENT CRUDE OIL FUTURES,PREV# DAY OPEN INTEREST
16996,463509.0,2019-07-08,ICE BRENT CRUDE OIL FUTURES,PREV# DAY OPEN INTEREST
16997,295191.0,2018-07-20,ICE BRENT CRUDE OIL FUTURES,PREV# DAY OPEN INTEREST
16998,444816.0,2019-07-09,ICE BRENT CRUDE OIL FUTURES,PREV# DAY OPEN INTEREST
16999,535856.0,2017-07-31,ICE BRENT CRUDE OIL FUTURES,PREV# DAY OPEN INTEREST

In [13]:
applemob['Commodity And Exchange'].value_counts()

NYMEX CRUDE OIL FUTURES                 8000
ICE BRENT CRUDE OIL FUTURES             7000
BRENT CRUDE OIL (DOLLARS PER BARREL)    1000
WTI CRUDE OIL (DOLLARS PER BARREL)      1000
Name: Commodity And Exchange, dtype: int64

In [14]:
applemob['Indicator'].value_counts()

PRICE IN USD                  2000
HIGH                          2000
OPEN                          2000
VOLUME                        2000
CHANGE                        2000
LOW                           2000
SETTLE                        2000
LAST                          1000
PREV# DAY OPEN INTEREST       1000
PREVIOUS DAY OPEN INTEREST    1000
Name: Indicator, dtype: int64