In [1]:
import pandas as pd
import numpy as np
import matplotlib as mlp
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

print("Done Import")

Done Import

In [2]:
pd.set_option('display.max_rows', 5)
pd.set_option('display.max_columns', None)

energy = pd.read_excel("energy-future-prices_src-intercontinental-exchange-ice.xlsx")
energy

,Value,Date,Product Id,ProductID_Contract,Exchange City,Super Region,Time Level,Unit,Source,Sub-Sector,Product Type,Exchange Country,Product Description
0,-1.00,2020-08-07,5629,5629_MAR21,SINGAPORE,GLOBAL DATA,DAILY,PRICE,INTERCONTINENTAL EXCHANGE - ICE,ENERGY FUTURES PRICES,CRUDE OIL AND REFINED,SINGAPORE,URALS NWE VS DATED BRENT SWAP
1,-2.05,2020-02-20,5629,5629_MAR21,SINGAPORE,GLOBAL DATA,DAILY,PRICE,INTERCONTINENTAL EXCHANGE - ICE,ENERGY FUTURES PRICES,CRUDE OIL AND REFINED,SINGAPORE,URALS NWE VS DATED BRENT SWAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17774,30.35,2020-03-19,95,95_MAY21,LONDON,GLOBAL DATA,DAILY,PRICE,INTERCONTINENTAL EXCHANGE - ICE,ENERGY FUTURES PRICES,CRUDE OIL AND REFINED PRODUCTS,UNITED KINGDOM,SINGAPORE NAPHTHA FUTURE
17775,28.16,2020-03-18,95,95_MAY21,LONDON,GLOBAL DATA,DAILY,PRICE,INTERCONTINENTAL EXCHANGE - ICE,ENERGY FUTURES PRICES,CRUDE OIL AND REFINED PRODUCTS,UNITED KINGDOM,SINGAPORE NAPHTHA FUTURE